### ISSUE TITLE
Cannot destroy active lambda function

### ISSUE THREAD

**Issue by bazo** [Kdyby/RabbitMq#20]
when restarting the workers from supervisor i always get this fatal error

it's raised here Kdyby/RabbitMq/Command/BaseConsumerCommand.php:74

**Comment by fprochazka** [comment]
I've never seen such error, how are you starting the consumer? what version of php do you have?

**Comment by bazo** [comment]
php version 5.6.8-1~dotdeb+wheezy.1

i'm running it via supervisor, the command is 

php path/cli rabbitmq:consumer queue

the error occurs everytime the process is stopped/restarted from the supervisor gui

**Comment by fprochazka** [comment]
try it like this

```
[program:rohlik_email_high]
command=/usr/bin/php /..../web/www/index.php rabbitmq:consumer -m 500 emails.high
directory=/..../web
user=www-data
autorestart=true
process_name=%(process_num)02d
numprocs=2
stopsignal=INT
stopwaitsecs=10
stdout_logfile=/..../web/log/consumer/emails.high.log
redirect_stderr=true
startsecs=1
```

the signal is the important part, but I'm attaching the whole block for future reference

**Comment by vojtech-dobes** [comment]
Same error can be seen when you kill running nette/tester with Control+C. So yeah, it seems like supervisor tries to stop your workers with SIGKILL. That's what you refer to, right @fprochazka?

**Comment by fprochazka** [comment]
@vojtech-dobes yes, I had problems with SIGKILL so consumer is not listening for it.

**Comment by fprochazka** [comment]
I've managed to reproduce it on localhost by killing the worker in the middle of processing messages

**Comment by fprochazka** [comment]
https://bugs.php.net/bug.php?id=62452

**Comment by fprochazka** [comment]
This should do it :)
