### ISSUE TITLE
Unable to use environment variable for settings

### ISSUE THREAD

**Issue by zeleznypa** [Kdyby/RabbitMq#22]
We need to get RabbitMQ host, port, etc. from environment variables

in neon we have:

```neon
extensions:
    rabbitmq: Kdyby\RabbitMq\DI\RabbitMqExtension

rabbitmq:
    connection:
        host: ::getenv(RABBITMQ_HOST)
        port: ::getenv(RABBITMQ_PORT)
        user: ::getenv(RABBITMQ_USER)
        password: ::getenv(RABBITMQ_PASSWORD)
```

But we give an assertion error that callback is not a valid string because of [this](https://github.com/Kdyby/RabbitMq/blob/master/src/Kdyby/RabbitMq/DI/RabbitMqExtension.php#L236)

**Comment by fprochazka** [comment]
I don't think I wanna support this. You can do something like

```php
<?php
return [
    'rabbitmq' => [
        'connection' => [
            'host' => getenv('RABBITMQ_HOST'),
        ]
    ]
];
```

and then register it in config

```yml
	includes:
		- rabbitmq.php
```

or use one of hundreds other ways to pass the ENV variable to the section.

**Comment by zeleznypa** [comment]
Thanks for tip, how to include environment variables other way.

I just tried it "[DG preferred way](https://github.com/nette/di/issues/8#issuecomment-63761287)"

Unfortunately it is just because the validation of *user* and *password. Whole other code fully support this way. I think, it will be more transparent, when whole configuration will be in one *.neon*. file instead of including the PHP code.

**Comment by fprochazka** [comment]
[How about this](https://github.com/rixxi/env#example-of-kdybydoctrine-configuration)?

**Comment by zeleznypa** [comment]
Thanks Filip
