### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by petrnemec** [Kdyby/RabbitMq#28]
Compatible PHP version(s) are not specified in composer.json

**Comment by fprochazka** [comment]
Is that a problem?

**Comment by petrnemec** [comment]
Since composer installs the latest (incompatible) version on PHP 5.3.x, it is a big problem!
The same problem is also with other extensions like Kdyby/Console or Kdyby/Doctrine.

**Comment by fprochazka** [comment]
Hmm, I didn't think of that. Dammit. Too bad this can't be probably fixed. Only for the versions in the future :-/ I would have to force push them and that is a no no.

**Comment by fprochazka** [comment]
I will do my best to always have the version constraint valid from now on. https://github.com/Kdyby/RabbitMq/commit/f310d62989a7d61eef216480058cdf4e3e30e6f8
