### ISSUE TITLE
 Argument 1 passed to Kdyby\RabbitMq\AnonymousConsumer::__construct() must be an instance of PhpAmqpLib\Connection\AMQPConnection, instance of Kdyby\RabbitMq\Connection given

### ISSUE THREAD

**Issue by zeleznypa** [Kdyby/RabbitMq#29]
When I tried to follow the manual and declare`AnonymousConsumer` by the following `config.neon`

```neon
rabbitmq:
	consumers:
		senderQueue:
			exchange: {name: 'sender-queue', type: topic}
			callback: [@Sender\RabbitMq\Consumers\SenderConsumer,'process']
```

By calling console command `index.php rabbitmq:anon-consumer -r 'sender1' senderQueue` the exception occured

```
Argument 1 passed to Kdyby\RabbitMq\AnonymousConsumer::__construct() must be an instance of PhpAmqpLib\Connection\AMQPConnection, instance of Kdyby\RabbitMq\Connection given
```
When I tried to fix it by changing the dependency definition, next exception occured:

```
[PhpAmqpLib\Exception\AMQPProtocolChannelException]  NOT_FOUND - no previously declared queue
```

**Comment by zeleznypa** [comment]
[This line](https://github.com/Kdyby/RabbitMq/blame/master/src/Kdyby/RabbitMq/AmqpMember.php#L237) is the reason for the second Exception;

**Comment by fprochazka** [comment]
@zeleznypa can you please test it?

**Comment by zeleznypa** [comment]
@fprochazka Sorry but I can't, because I moved from the company that have this problem.

**Comment by akadlec** [comment]
Still not fixed:
```
[PhpAmqpLib\Exception\AMQPProtocolChannelException]
  NOT_FOUND - no previously declared queue
```
