### ISSUE TITLE
Update dependency to php-amqplib/php-amqplib respectively to php-amqplib/RabbitMqBundle

### ISSUE THREAD

**Issue by tomasstrejcek** [Kdyby/RabbitMq#30]
thx

**Comment by fprochazka** [comment]
@tomasstrejcek what features from `RabbitMqBundle` are missing?

**Comment by brosland** [comment]
warning from composer:

Package videlalvaro/php-amqplib is abandoned, you should avoid using it. Use php-amqplib/php-amqplib instead.

Do you know about it?

**Comment by fprochazka** [comment]
@brosland yes

**Comment by chaintan17** [comment]
Please check this pull request @fprochazka 
https://github.com/Kdyby/RabbitMq/pull/36
