### ISSUE TITLE
Next major based on jakubkulhan/bunny?

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/RabbitMq#35]
Consider dropping `php-amqplib/php-amqplib` and rewriting to a better client - which would probably make this only a thin integration into Nette with compatibility layer.

Also, it might be better to create new package instead.

**Comment by tomasstrejcek** [comment]
new library would be better way..

**Comment by fprochazka** [comment]
@tomasstrejcek true

**Comment by tomasstrejcek** [comment]
Will you be moving in this direction some time in foreseeable future? :) Perhaps at least start with new repo and file structure proposition and then wait for community to pull their weight? :)

**Comment by fprochazka** [comment]
Nobody picked it up yet? :)

**Comment by foxycode** [comment]
I believe this is solution: https://github.com/gameeapp/nette-rabbitmq

**Comment by VBoss** [comment]
This package wont probably switch to another implementation, but there is alternative as mentioned.
