### ISSUE TITLE
AMQPRuntimeException: Invalid frame type 60

### ISSUE THREAD

**Issue by fabik** [Kdyby/RabbitMq#47]
Hello, I've been using this library for a long time without any problems. Since yesterday I sometimes get this error when a message is consumed. It only happens from time to time. Independently, @mstrouhal told me he has the same problem as well. Has anyone else experienced this problem? Do you have any ideas what causes it?

The server is running PHP 7.0.8 and RabbitMQ 3.6.1 on Ubuntu 14.04. The dependencies are in these versions: kdyby/rabbitmq@116312df4194886a48461a6cf579b1d306aab553, videlalvaro/php-amqplib@fa2f0d4410a11008cb36b379177291be7ee9e4f6

![error](https://cloud.githubusercontent.com/assets/816866/17453201/58d616c2-5b78-11e6-84a0-c424230cf683.png)

**Comment by mstrouhal** [comment]
Hi folks. I've been using Kdyby\RabbitMQ with millions of messages per day. This issue started to occur yesterday on all of my servers and now it is spamming error logs constantly. Servers are running PHP 5.6.24 on Debian (Wheezy and Jessie). Do you have any recommendations to solve the problem?

**Comment by mstrouhal** [comment]
After upgrading to newest RabbitMQ server + increasing timeout for connection handshake from 10 seconds to 20 - the issue is gone without any further occurrence.

**Comment by fabik** [comment]
Upgrade to RabbitMQ 3.6.5 probably solved the problem. Something was probably broken in RabbitMQ 3.6.1. I hope it will not randomly occur again.
