### ISSUE TITLE
Compatibility with ReactPHP

### ISSUE THREAD

**Issue by srigi** [Kdyby/RabbitMq#49]
Hi, does anyone know how to make this lib compatible with ReactPHP? The issue can be seen in this simplified example:

``` php
class ServerConsumer implements IConsumer
{
    private $app;

    public function __construct($port, Ratchet\MessageComponentInterface $app)
    {
        $this->app = $app;

        $httpServer = new Ratchet\Http\HttpServer(new Ratchet\WebSocket\WsServer($app));
        $ioServer = Ratchet\Server\IoServer::factory($httpServer, $port);
        $ioServer->run();
    }

    public function process(AMQPMessage $message)
    {
        $this->app->notifyConnectedClients($message);

        return TRUE;
    }
}
```

The problem is that `$ioServer->run()` is _blocking_. Then `process()` callback will never run upon received message from queue. Is there any good solution to this issue?

**Comment by fprochazka** [comment]
Sadly, I think that is impossible with `php-amqplib/php-amqplib`. You'll have to use [bunny](https://github.com/jakubkulhan/bunny).
