### ISSUE TITLE
Compatibility with Nette 3.0

### ISSUE THREAD

**Issue by miloshavlicek** [Kdyby/RabbitMq#54]
Update dependencies

**Comment by matak** [comment]
any progress? any working fork?

**Comment by enumag** [comment]
See #72.

**Comment by matak** [comment]
- kdyby/rabbitmq dev-master requires nette/di ~2.4@dev -> satisfiable by nette/di[v2.4.0, v2.4.1, v2.4.10, v2.4.11, v2.4.12, v2.4.13, v2.4.14, v2.4.15, v2.4.16, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.4.x-dev].

maybe it is neccessary to update composer.json? to be compatible with nette 3.0.0?
