### ISSUE TITLE
Update for PHP 7.2

### ISSUE THREAD

**Issue by davidkudera** [Kdyby/RabbitMq#62]
Right now kdyby/rabbitmq can't be used with PHP 7.2, because of usage of `Nette\Object` class.

**Comment by enumag** [comment]
This repository is no longer actively maintained. But if you send a pull request I can merge it for you.

**Comment by kratkyzobak** [comment]
@davidkudera I'm currently working on PHP 7.2 support. Before it can make to master, you're free to use version `dev#322f2d96085c0ccc148415542cba82541ac64798` in your `composer.json`.

**Comment by davidkudera** [comment]
@kratkyzobak Hi and thank you :+1:

**Comment by BigOHenry** [comment]
how can i use `dev#322f2d96085c0ccc148415542cba82541ac64798` in composer? I still getting error about invalid string

**Comment by enumag** [comment]
You would have to add the fork repository to your composer.json.

https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

**Comment by VBoss** [comment]
PHP 71+ support is released https://github.com/Kdyby/RabbitMq/releases/tag/v2.0.0
