### ISSUE TITLE
Add version tags to commits

### ISSUE THREAD

**Issue by WyskyNet** [Kdyby/RabbitMq#68]
Hi,
can you add some version tags to commits? We need at least tagged commit id b95342baa3a75cea930fcd0efbf5b84479d02d34 ... that's latest library commit that works on Nette 2.3., so tag can be Nette2.3 or rather v1.1.1.

Thx

**Comment by VBoss** [comment]
If you need specific commit as some version you can add to composer `"kdyby/rabbitmq": "dev-master#b95342baa3a75cea930fcd0efbf5b84479d02d34 as v1.1.1"`.
Nette 2.3 is no longer supported you can use Nette 3 with latest release https://github.com/Kdyby/RabbitMq/releases/tag/v2.0.0
